USE db_redes_sociais

INSERT INTO tb_usuarios
VALUES (1, 'NICK', 'NICKNIK', 'NICK123', 'FOTODOPERFIL'),
(2, 'VINICIUS', 'VINI', 'SENHADOVINI', 'FOTODOVINI'),
(3, 'THAINA','THAI', 'THAINA321', 'FOTODATHAINA');

INSERT INTO tb_grupos
VALUES ('GRUPO DE VENDAS', 'NESTE GRUPO FAZEMOS VENDAS', 'FOTODOGRUPO', 2, 2),
('GRUPO DE ANIMAIS', 'AMAMOS ANIMAIS FOFINHOS', 'FOTODEANIMAIS', 1, 3),
('GRUPO DOS DEVS DA GENERATION', 'GRUPO ONDE JOGAMOS AMONG US NO FINAL DO DIA', 'FOTODOBOAZ', 3, 1);

INSERT INTO tb_postagens
VALUES ('VEJAM MEU NOVO GATINHO', 'ADOTEI ESSE GATINHO ONTEM', 'FOTO DO GATO', '27/07/2022', 2, 2),
('NOVO EMPREGO', 'CONSEGUI NOVO EMPREGO DE DEV', 'FOTODAEMPRESA', '28/07/2022', 3, 3);


SELECT descricao FROM tb_grupos
WHERE descricao LIKE '%rupo%';

SELECT Id_usuarios FROM tb_usuarios
WHERE Id_usuarios BETWEEN 1 AND 5;